# Generated by Django 3.0.2 on 2023-02-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
