# Generated by Django 3.0.5 on 2023-03-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20230307_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='rbc',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='wbc',
        ),
    ]
