# Generated by Django 3.0.5 on 2023-03-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20230313_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='government',
            field=models.ImageField(blank=True, null=True, upload_to='government/government/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Patient/'),
        ),
    ]
