# Generated by Django 3.0.5 on 2023-03-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20230313_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='government',
        ),
    ]
