# Generated by Django 3.0.5 on 2023-03-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_remove_patient_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/government/'),
        ),
    ]
