# Generated by Django 3.0.2 on 2023-02-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='expire_date',
        ),
    ]
