# Generated by Django 3.0.5 on 2023-03-08 03:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_remove_bloodrequest_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='rbc',
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='wbc',
            field=models.PositiveIntegerField(default=datetime.datetime(2023, 3, 8, 3, 54, 3, 759141, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
