# Generated by Django 3.0.5 on 2023-03-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_auto_20230308_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='rbc',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='wbc',
            field=models.CharField(max_length=40),
        ),
    ]
